# Generated by Django 3.1.12 on 2025-11-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20251121_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='area_km2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='buildings_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='file_size_mb',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='highways_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='landuse_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='natural_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='total_elements',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='triangles_estimate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='water_count',
            field=models.IntegerField(default=0),
        ),
    ]
