# Generated by Django 3.1.12 on 2025-11-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20251121_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='export_format',
            field=models.CharField(default='json', max_length=10),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='is_export',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='original_file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
