# Generated by Django 3.1.12 on 2025-11-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20251121_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='export_format',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='file_format',
            field=models.CharField(default='json', max_length=10),
        ),
    ]
