# Generated by Django 3.1.12 on 2025-11-21 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20251121_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='file_format',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='is_export',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='original_file_name',
        ),
    ]
