# Generated by Django 3.1.12 on 2025-11-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20251121_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='glb_export_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='glb_file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='has_glb_export',
            field=models.BooleanField(default=False),
        ),
    ]
