# Generated by Django 3.1.12 on 2025-11-23 01:13

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20251122_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AlterModelOptions(
            name='usermodel',
            options={},
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='area_km2',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='buildings_count',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='downloads',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='highways_count',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='landuse_count',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='natural_count',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='triangles_estimate',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='views',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='water_count',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='glb_file',
            field=models.FileField(blank=True, null=True, upload_to=main.models.user_export_path),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='file_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='glb_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='title',
            field=models.CharField(default='Proiect Nou', max_length=255),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='main.user'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
