# Generated by Django 3.1.12 on 2025-11-23 01:20

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20251123_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.user_thumbnail_path),
        ),
    ]
