# Generated by Django 3.1.12 on 2025-11-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_usermodel_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='user_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
