# Generated by Django 3.1.12 on 2025-11-24 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_usermodel_user_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='area_km2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='building_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='highway_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='landuse_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='natural_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='other_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='water_count',
            field=models.IntegerField(default=0),
        ),
    ]
