# Generated by Django 3.1.12 on 2025-11-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20251124_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='camera_position',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='thumbnail_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
