# Generated by Django 3.1.12 on 2025-12-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20251126_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='public_view_count',
            field=models.IntegerField(default=0, help_text='Număr de vizualizări pentru modelele publice'),
        ),
    ]
