# Generated by Django 3.1.12 on 2025-12-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_usermodel_public_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='public_view_count',
            field=models.IntegerField(default=0),
        ),
    ]
