# Generated by Django 3.1.12 on 2025-12-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20251210_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_models', to='main.User'),
        ),
    ]
